{
	[1]={
		["name"]="Fireball",
		["words"]="",
		["target"]="target",
		["element"]="fire",
		["dmg"]={4,8},
		["mana"]=5,
	},
	[2]={
		["name"]="Magic Missile",
		["words"]="",
		["target"]="target",
		["element"]="fire",
		["dmg"]={4,8},
		["mana"]=2,
	},
	[3]={
		["name"]="blank",
		["words"]="",
		["target"]="target",
		["element"]="none",
		["dmg"]={0,0},
		["mana"]=1,
	},
	[4]={
		["name"]="Heal Self",
		["words"]="",
		["target"]="self",
		["element"]="magic",
		["dmg"]={-1,-4},
		["mana"]=5,
	},
}